const ActionTypes = {
  OWNER_SITE_LIST: "OWNER_SITE_LIST",
  OWNER_SITE_DETAIL: "OWNER_SITE_DETAIL",
  OWNER_SITE_CREATE: "OWNER_SITE_CREATE",
  OWNER_SITE_UPDATE: "OWNER_SITE_UPDATE",
  OWNER_SITE_DELETE: "OWNER_SITE_DELETE"
};

export default ActionTypes;
