
const ActionTypes = {
  AUTH_SITE_LOGIN: "AUTH_SITE_LOGIN",
  AUTH_SITE_LOGOUT: "AUTH_SITE_LOGOUT",
  AUTH_SITE_REGISTER: "AUTH_SITE_REGISTER",
  AUTH_SITE_FORGOT: "AUTH_SITE_FORGOT",
  GET_SITE_ME: "GET_SITE_ME",
  AUTH_SITE_CLEAR: "AUTH_SITE_CLEAR"
}

export default ActionTypes;