const ActionTypes = {
  PET_SITE_LIST: "PET_SITE_LIST",
  PET_SITE_DETAIL: "PET_SITE_DETAIL",
  PET_SITE_CREATE: "PET_SITE_CREATE",
  PET_SITE_UPDATE: "PET_SITE_UPDATE",
  PET_SITE_DELETE: "PET_SITE_DELETE"
};

export default ActionTypes;
